=== FreifeldRoyi/quadcoreforum/src/testing/oldpersistentdata/QuadCoreForumDB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">




	<xsd:complexType name="NamedComponentType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"></xsd:element>
			<xsd:element name="description" type="xsd:string"></xsd:element>
			<xsd:element name="numOfMessages" type="NonNegativeLong">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="MemberType">
		<xsd:sequence>
			<xsd:element name="userID" type="NonNegativeLong">
			</xsd:element>
			<xsd:element name="username" type="xsd:string"></xsd:element>
			<xsd:element name="e-mail">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value=".+(@).+"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="password" type="xsd:string"></xsd:element>
			<xsd:element name="lastName" type="xsd:string"></xsd:element>
			<xsd:element name="firstName" type="xsd:string"></xsd:element>
			<xsd:element name="numOfPostedMessages" type="xsd:long"></xsd:element>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="postedMessagesIDs" type="xsd:long"></xsd:element>
			</xsd:sequence>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="privileges">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="ADD_SUBJECT"></xsd:enumeration>
							<xsd:enumeration value="DELETE_SUBJECT"></xsd:enumeration>
							<xsd:enumeration value="OPEN_THREAD"></xsd:enumeration>
							<xsd:enumeration value="REPLY_TO_MESSAGE"></xsd:enumeration>
							<xsd:enumeration value="DELETE_THREAD"></xsd:enumeration>
							<xsd:enumeration value="DELETE_MESSAGE"></xsd:enumeration>
							<xsd:enumeration value="EDIT_MESSAGE"></xsd:enumeration>
							<xsd:enumeration value="VIEW_ALL"></xsd:enumeration>
							<xsd:enumeration value="ADD_SUB_SUBJECT"></xsd:enumeration>
							<xsd:enumeration value="SET_MODERATOR"></xsd:enumeration>
							<xsd:enumeration value="EDIT_SUBJECT"></xsd:enumeration>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element></xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="SubjectType">
		<xsd:complexContent>
			<xsd:extension base="NamedComponentType">
				<xsd:sequence>
					<xsd:element name="subjectID"
						type="NonNegativeLong">
					</xsd:element>

					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="subSubjectsIDs"
							type="NonNegativeLong">
						</xsd:element>
					</xsd:sequence>

					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="threadsIDs"
							type="NonNegativeLong">
						</xsd:element>
					</xsd:sequence>


					<xsd:element name="lastAddedMessageID"
						type="NonNegativeLong" minOccurs="0" maxOccurs="1">
					</xsd:element>
					<xsd:element name="isToLevel" type="xsd:boolean"></xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
    
    <xsd:complexType name="MessageType">
    	<xsd:sequence>
    		<xsd:element name="messageID" type="NonNegativeLong"></xsd:element>
    		<xsd:element name="author" type="xsd:long"></xsd:element>
    		<xsd:element name="title" type="xsd:string"></xsd:element>
    		<xsd:element name="content" type="xsd:string"></xsd:element>
    		<xsd:element name="postTime" type="xsd:dateTime"></xsd:element>
    		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    			<xsd:element name="repliesIDs" type="NonNegativeLong"></xsd:element>
    		</xsd:sequence>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ThreadType">
    	<xsd:sequence>
    		<xsd:element name="threadID" type="NonNegativeLong"></xsd:element>
            <xsd:element name="topic" type="xsd:string"></xsd:element>
            <xsd:element name="startMessageID" type="NonNegativeLong"></xsd:element>
    		<xsd:element name="lastMessageID" type="NonNegativeLong"></xsd:element>
    		<xsd:element name="numOfViews" type="NonNegativeLong">
    		</xsd:element>
    		<xsd:element name="numOfResponses" type="NonNegativeLong">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

	<xsd:element name="ForumType">
  	  <xsd:complexType>
    		<xsd:sequence>
    			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    				<xsd:element name="members" type="MemberType">
    				</xsd:element>
    			</xsd:sequence>
    			<xsd:sequence minOccurs="0" maxOccurs="unbounded"><xsd:element name="subjects" type="SubjectType">
    			</xsd:element></xsd:sequence>
    			<xsd:sequence minOccurs="0" maxOccurs="unbounded"><xsd:element name="threads" type="ThreadType">
    			</xsd:element></xsd:sequence>
    			<xsd:sequence minOccurs="0" maxOccurs="unbounded"><xsd:element name="messages" type="MessageType">
    			</xsd:element></xsd:sequence>
    		</xsd:sequence>
  	  </xsd:complexType>
	</xsd:element>



	<xsd:simpleType name="NonNegativeLong">
		<xsd:restriction base="xsd:long">
			<xsd:minInclusive value="0"></xsd:minInclusive>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== FreifeldRoyi/quadcoreforum/src/testing/oldpersistentdata/InitialDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<ForumType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QuadCoreForumDB.xsd">
  <members>
    <userID>0</userID>
    <username>username</username>
    <e-mail>test@test</e-mail>
    <password>password</password>
    <lastName>lastName</lastName>
    <firstName>firstName</firstName>
    <numOfPostedMessages>0</numOfPostedMessages>
    <postedMessagesIDs>0</postedMessagesIDs>
    <privileges>ADD_SUBJECT</privileges>
  </members>
  <subjects>
    <name>name</name>
    <description>description</description>
    <numOfMessages>0</numOfMessages>
    <subjectID>0</subjectID>
    <subSubjectsIDs>0</subSubjectsIDs>
    <threadsIDs>0</threadsIDs>
    <lastAddedMessageID>0</lastAddedMessageID>
    <isToLevel>false</isToLevel>
  </subjects>
  <threads>
    <threadID>0</threadID>
    <topic>topic</topic>
    <startMessageID>0</startMessageID>
    <lastMessageID>0</lastMessageID>
    <numOfViews>0</numOfViews>
    <numOfResponses>0</numOfResponses>
  </threads>
  <messages>
    <messageID>0</messageID>
    <author>0</author>
    <title>title</title>
    <content>content</content>
    <postTime>2001-12-31T12:00:00</postTime>
    <repliesIDs>0</repliesIDs>
  </messages>
</ForumType>
